### ISSUE TITLE
Could this be integrated into posh-git? That way it would come with GitHub for Windows

### ISSUE THREAD

**Issue by shanselman** [samneirinck/posh-docker#1]
Could this be integrated into posh-git? That way it would come with GitHub for Windows

**Comment by samneirinck** [comment]
It could, but would it not be a conflict of interests? It makes sense to bundle posh-git with GitHub for Windows since it's all git related, but docker is another story and I can imagine people frowning upon bundling software they do not want.

**Comment by shanselman** [comment]
I asked because I'm having trouble with this and posh-git in GitHub for
Windows' Git Shell...when posh-docker is installed I'm not getting both to
work reliably together.

On Mon, Nov 30, 2015 at 11:52 PM, Sam Neirinck notifications@github.com
wrote:

> It could, but would it not be a conflict of interests? It makes sense to
> bundle posh-git with GitHub for Windows since it's all git related, but
> docker is another story and I can imagine people frowning upon bundling
> software they do not want.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samneirinck/posh-docker/issues/1#issuecomment-160886757
> .

## 

Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by samneirinck** [comment]
Could you post the output of the docker installation script, as well as the contents of $PROFILE (`notepad $PROFILE`)?

I have them both installed in my profile.

**Comment by shanselman** [comment]
Ah, let me check. I don't have it installed in my profile, Poshgit is
injected by G4W (GitShell)

On Tue, Dec 1, 2015 at 9:02 AM, Sam Neirinck notifications@github.com
wrote:

> Could you post the output of the docker installation script, as well as
> the contents of $PROFILE (notepad $PROFILE)?
> 
> I have them both installed in my profile.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samneirinck/posh-docker/issues/1#issuecomment-161032334
> .

## 

Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by samneirinck** [comment]
I've updated the installation procedure. It uses powershellgallery.com to install now (which is nuget-based). This should make it super-easy to install, and hopefully solve your issue as well.

To make sure the previous version is not causing conflicts, could you remove the old installation by editing your profile (via `notepad $PROFILE`), and remove the posh-docker references.

Then, follow the new installation & usage directions. Hopefully that solves your issue!

**Comment by stuartleeks** [comment]
Bundling this with the VS Docker tools might be interesting :-)

**Comment by andymac4182** [comment]
Ideally this would be built in with Docker for Windows Beta :smile:

**Comment by andymac4182** [comment]
Turns out I missed that it was coming :) https://github.com/docker/docker/tree/master/contrib/completion/powershell https://twitter.com/friism/status/749034995377770496

**Comment by samneirinck** [comment]
Sorry for the delay, the core functionality has indeed been merged into docker contrib. I think an ideal scenario would be if all development is done in there, since there are many more eyes over there.

**Comment by samneirinck** [comment]
I'm going to close this one for now, the official docker for windows docs now mention installing this extension as well, so that should help discoverability. https://docs.docker.com/docker-for-windows/#/set-up-tab-completion-in-powershell.
