### ISSUE TITLE
No effect after installing

### ISSUE THREAD

**Issue by jakobrosenberg** [samneirinck/posh-docker#14]
I tried the install instructions in your readme as well as the ones found [here](https://docs.docker.com/docker-for-windows/).

Neither method had any affect on autocompletion.

I'm on Windows 10 x64 (Build 14986) / Docker 1.13

``Get-Module posh-docker`` returns

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.6.0      posh-docker                         ConvertFrom-Docker
```

**Comment by samneirinck** [comment]
Seems like an issue with Docker 1.13, I'll keep you up to date at the following ticket: #15
