### ISSUE TITLE
Support for Docker 1.13 management commands

### ISSUE THREAD

**Issue by kalugny** [samneirinck/posh-docker#15]
Docker 1.13 changed the command line interface.
Can you add support for this?
Thanks a lot!

**Comment by samneirinck** [comment]
Thanks, I'll have a look.

**Comment by samneirinck** [comment]
posh-docker version 0.7.1 now has support for Docker 1.13. Please update via `Update-Module posh-docker` and let met know if it works. You will need to launch a new terminal window after updating.

**Comment by samneirinck** [comment]
I'll close this, if you have further issues, please let me know.
