### ISSUE TITLE
Support image names

### ISSUE THREAD

**Issue by giggio** [samneirinck/posh-docker#6]
Right now it seems to only get container names, but it would be nice to get image names for `docker run`, `docker rmi`, and any other command that works with images.
Right now, `docker run` will show container names if you tab, which is wrong.

**Comment by samneirinck** [comment]
This is indeed something I would like to add in the future.

**Comment by samneirinck** [comment]
This is now implemented in 0.5.1.

Let me know if it works for you! Run `Update-Module posh-docker` and restart your console to see if it works.
